export type LessonPackTeaching = {
  teaching: string;
  language: string[];
  activityGuide: string;
  relatedTopic?: string;
};

export const LESSON_PACK_TEACHING: Record<string, LessonPackTeaching> = {
  "active-verbs-beginner-esl": { teaching: "Use these high-frequency action verbs as commands first, then reuse the same pictures for present continuous and can / can’t practice. Movement gives beginners a clear meaning before they need to produce a sentence.", language: ["Can you jump? Yes, I can.", "What is she doing? She is running."], activityGuide: "For Action Charades, let one learner mime a card while the class guesses the verb, then ask a stronger learner to make a full sentence.", relatedTopic: "actions" },
  "after-school-verbs-beginner-esl": { teaching: "After-school actions are useful for talking about real routines, preferences, and simple time expressions. Sequence the cards before learners describe what they do when school finishes.", language: ["What do you do after school?", "I do my homework, then I play."], activityGuide: "Turn the activity into a timetable race: pairs put the six actions in a believable order and explain one difference from their own routine." },
  "appearance-adjectives-beginner-esl": { teaching: "Teach appearance words through descriptions rather than isolated labels. The cards support careful listening as learners distinguish tall and short, young and old, or beautiful and handsome.", language: ["He is tall and young.", "What does she look like?"], activityGuide: "In Describe and Find, one learner describes a card character while their partner identifies the matching image without seeing the speaker’s card." },
  "body-parts-vocabulary-beginner-esl": { teaching: "Body-part vocabulary works best when learners can point, touch, or move as they listen. It is a natural bridge from simple nouns to classroom instructions and basic health language.", language: ["Touch your nose.", "I have got two hands."], activityGuide: "Use the body-part relay as a listening check: display a card, then teams touch the matching body part before naming it.", relatedTopic: "body" },
  "classroom-actions-verbs-beginner-esl": { teaching: "These verbs help learners understand the English used to run a lesson: listen, look, write, read, and work together. Practise them with real classroom instructions, not only picture naming.", language: ["Please open your book.", "Listen and repeat."], activityGuide: "For the activity, mix instruction cards with a few deliberately wrong actions. Learners follow only the instruction that matches the picture." },
  "classroom-objects-vocabulary-beginner-esl": { teaching: "Use real items alongside the cards so classroom-object vocabulary immediately becomes useful. Once the nouns are secure, add positions such as on the desk and in the bag.", language: ["What is this? It’s a ruler.", "Put the pencil in your bag."], activityGuide: "Use a classroom scavenger hunt: learners find the real object, point to it, and say the word before returning to their team.", relatedTopic: "classroom-objects" },
  "clothing-vocabulary-beginner-esl": { teaching: "Teach clothes as outfits, then connect the vocabulary to weather and occasions. A few cards can generate meaningful descriptions instead of a long clothing list.", language: ["She is wearing a dress.", "I wear a jacket when it’s cold."], activityGuide: "For dress-for-the-weather, pairs choose clothing cards for a weather card and explain one choice to the class.", relatedTopic: "clothes" },
  "colors-adjectives-beginner-esl": { teaching: "Colour words become more memorable when learners use them to describe familiar objects, clothes, and classroom items. Combine the cards with a real-object hunt to move from recognition to speech.", language: ["What colour is it? It’s green.", "I can see a red book."], activityGuide: "In Color Corners, place colour cards around the room. Call an object or show a picture and have learners move to its colour." },
  "creative-activities-verbs-beginner-esl": { teaching: "Creative-action verbs work well with classroom materials and project language. Learners can connect each verb to a genuine task rather than only acting it out.", language: ["Let’s draw a picture.", "What are you making?"], activityGuide: "Use Creative Corners by assigning one verb to each corner. Learners move to the matching action, mime it, then say the word." },
  "directions-prepositions-beginner-esl": { teaching: "Direction words need movement and a visible route. Use the cards with a classroom map or tape arrows on the floor so learners can follow and give instructions.", language: ["Turn left at the bank.", "Go straight ahead."], activityGuide: "Create a simple floor map for the route activity. One learner gives directions while a partner walks a counter or character to the destination." },
  "family-vocabulary-beginner-esl": { teaching: "Family vocabulary supports personal speaking but does not require learners to share private details. Start with card families or fictional characters, then allow optional connections to their own family.", language: ["Who is this? This is my brother.", "She has got two sisters."], activityGuide: "For the activity, give pairs a small fictional family tree. They place the cards and introduce one family member to another pair." },
  "feelings-adjectives-beginner-esl": { teaching: "Feelings cards make abstract emotion words visible and support a safe class check-in. They also work well with story characters, facial expressions, and simple reasons.", language: ["How do you feel? I feel happy.", "Why is he sad?"], activityGuide: "Run Emotion Charades with silent faces and body poses. After guessing, ask learners to suggest a simple reason for that feeling.", relatedTopic: "emotions" },
  "five-senses-verbs-beginner-esl": { teaching: "Sense verbs help learners describe what they notice rather than only naming objects. Use real classroom-safe sounds, textures, and pictures to make see, hear, smell, taste, and feel meaningful.", language: ["What can you hear?", "It feels soft."], activityGuide: "Set up five simple stations with safe objects or recordings. Learners choose the matching sense-verb card and make one observation." },
  "food-actions-verbs-beginner-esl": { teaching: "Food-action verbs give learners a useful sequence for talking about cooking, meals, and kitchen routines. Arrange the cards as a process before asking for spoken instructions.", language: ["First, wash the apple.", "We cut the bread and eat it."], activityGuide: "For Kitchen Action Corners, learners move to the action that fits a food picture, then explain what happens first or next." },
  "food-adjectives-beginner-esl": { teaching: "Food adjectives help learners say more than ‘I like it’. Use the cards to contrast tastes and textures, then connect the words to familiar foods.", language: ["The lemon is sour.", "Do you like sweet food?"], activityGuide: "Make a taste survey with picture cards. Learners predict whether a food is sweet, salty, sour, or spicy, then compare answers." },
  "friends-and-communication-verbs-beginner-esl": { teaching: "Communication verbs fit naturally with partner work, introductions, and social classroom routines. Give learners a clear reason to use the verbs while they meet, talk, and work together.", language: ["Nice to meet you.", "Can I introduce my friend?"], activityGuide: "Use a meet-and-mingle grid. Learners complete a small communication task at each stop, such as introducing a partner or asking a question." },
  "games-and-play-verbs-beginner-esl": { teaching: "Play verbs are ideal for active ESL lessons because learners can demonstrate the meaning and talk about what they enjoy. Use the cards to practise likes, abilities, and invitations.", language: ["Do you like playing chess?", "Let’s play together."], activityGuide: "For a game-choice survey, learners ask classmates which activity they like and make a simple class chart from the card results." },
  "home-chores-verbs-beginner-esl": { teaching: "Chore vocabulary links action verbs to daily responsibilities and home routines. Keep the language practical with pictures of jobs learners recognise, then sequence or divide the tasks.", language: ["I make my bed.", "Who does the washing up?"], activityGuide: "Use a weekly chore chart. Pairs place cards on different days and explain one job they do at home or in a fictional family." },
  "home-furniture-vocabulary-beginner-esl": { teaching: "Furniture cards are especially useful with prepositions because learners can place objects around a room. Start by naming room items, then describe where they are.", language: ["The lamp is next to the bed.", "There is a sofa in the living room."], activityGuide: "For the room-design activity, pairs arrange furniture cards in a simple room plan and describe the finished room to another pair." },
  "jobs-vocabulary-beginner-esl": { teaching: "Jobs vocabulary supports community topics, role play, and the question ‘What does a … do?’ Use the cards to connect people with workplaces, tools, and everyday responsibilities.", language: ["What does a doctor do?", "A firefighter helps people."], activityGuide: "Run Job Charades by giving one learner a job card to mime. The class guesses, then names one place that person might work." },
  "kitchen-objects-vocabulary-beginner-esl": { teaching: "Kitchen-object vocabulary becomes useful when learners sort, set a table, or follow a simple recipe sequence. Use real or toy items where possible to make the words concrete.", language: ["Pass me a spoon, please.", "The cup is on the table."], activityGuide: "For a table-setting relay, teams place object cards beside a plate card and say each item before the next learner takes a turn." },
  "learning-and-study-verbs-beginner-esl": { teaching: "Study verbs help learners talk about what happens in English class and how they learn. They can make classroom routines clearer while building vocabulary for subjects and homework.", language: ["I study English on Monday.", "Please remember this word."], activityGuide: "Use a learning-plan activity: pairs choose cards for a short study routine and explain which action comes first." },
  "morning-routine-verbs-beginner-esl": { teaching: "Morning-routine cards provide an easy sequence for present simple, time phrases, and first / then / finally. Learners can describe a fictional routine before sharing anything personal.", language: ["I wake up at seven.", "First I get dressed, then I eat breakfast."], activityGuide: "Give teams mixed cards and ask them to build a morning sequence. Award a point for each correct full sentence.", relatedTopic: "daily-routines" },
  "movement-prepositions-beginner-esl": { teaching: "Movement prepositions need physical routes, not definitions. Use chairs, hoops, and classroom objects so learners can see and perform into, onto, across, around, through, and over.", language: ["Walk around the chair.", "Jump over the line."], activityGuide: "Build a safe preposition obstacle course. One learner gives an instruction card while another completes the movement." },
  "nature-vocabulary-beginner-esl": { teaching: "Nature vocabulary invites observation, sorting, and describing outdoor places. The cards work well with seasons, colours, habitats, and simple environmental language.", language: ["I can see a butterfly.", "The river is near the forest."], activityGuide: "Use a nature hunt with picture cards. Learners find real examples outside or match the cards to a scene picture, then report what they found." },
  "numbers-vocabulary-beginner-esl": { teaching: "Number words are stronger when learners count real objects, take turns, and listen for a specific quantity. Keep the focus on meaning by pairing the cards with counters or classroom items.", language: ["How many pencils are there?", "There are six pencils."], activityGuide: "For a number hunt, place groups of objects or picture cards around the room. Learners count, find the matching number card, and say the total." },
  "opposites-adjectives-beginner-esl": { teaching: "Opposites are best introduced in pairs so learners notice contrast: clean and dirty, open and closed, full and empty. Use real objects and quick changes to make each pair visible.", language: ["Is the door open or closed?", "The glass is full."], activityGuide: "Run an opposites relay: show one card and teams race to find or hold up its opposite before making a sentence." },
  "outdoor-adventures-verbs-beginner-esl": { teaching: "Outdoor-adventure verbs give learners language for holidays, nature, and weekend plans. The pictures support useful verb phrases such as go hiking and go camping.", language: ["I want to go camping.", "Can you climb a mountain?"], activityGuide: "Create an adventure trail with destination pictures. Pairs choose an activity card for each place and explain their choice." },
  "personality-adjectives-beginner-esl": { teaching: "Personality adjectives are easier to teach through behaviour and examples than through translation. Use characters and situations so learners can see what kind, helpful, brave, polite, friendly, and smart mean.", language: ["She is kind and helpful.", "He is polite to his teacher."], activityGuide: "For Kindness Walk, give pairs a situation card. They choose a personality adjective that fits and act out a short response." },
  "place-prepositions-beginner-esl": { teaching: "Place prepositions become clear when learners position real objects or cards. Keep the target language short and repeat the same spatial relationships in several layouts.", language: ["The ball is under the chair.", "The book is between the bags."], activityGuide: "Use a classroom treasure map. Partners listen to a location instruction, place a token, and check it against the picture card." },
  "places-adjectives-beginner-esl": { teaching: "Place adjectives help learners describe a town, room, or scene in more detail. Contrast pairs such as noisy and quiet or crowded and empty with visual settings.", language: ["The market is crowded.", "This room is dark and quiet."], activityGuide: "In Adjective Stations, display scene pictures around the room. Learners choose the adjective card that best describes each scene and justify one answer." },
  "places-in-town-vocabulary-beginner-esl": { teaching: "Town-place vocabulary supports maps, directions, and everyday community language. Start with the places learners know, then ask where they go for different needs.", language: ["Where is the library?", "I go to the bakery to buy bread."], activityGuide: "Create a simple town map. Learners place location cards, then ask and answer where a person should go." },
  "school-subjects-vocabulary-beginner-esl": { teaching: "School-subject cards encourage personal speaking because learners can talk about their timetable and preferences. They also support days of the week and simple reasons.", language: ["What is your favourite subject?", "I like science because it is fun."], activityGuide: "For Subject Corners, give each corner a subject. Learners move to a favourite, then interview a partner about their choice." },
  "size-and-shape-adjectives-beginner-esl": { teaching: "Size and shape words are easiest to remember through comparison. Use classroom objects, drawings, and pairs of cards to show big, small, huge, tiny, long, and short.", language: ["The elephant is huge.", "Which pencil is longer?"], activityGuide: "Run a size hunt: teams find or draw objects that match each adjective card, then compare their examples with another team." },
  "speaking-skills-verbs-beginner-esl": { teaching: "Speaking-skill verbs give learners practical language for classroom interaction, from asking and answering to explaining and sharing ideas. Practise them in short supported exchanges.", language: ["Can you repeat that, please?", "I want to share my idea."], activityGuide: "Use conversation stations with a verb card at each table. Pairs complete a short speaking task that requires that action." },
  "speed-and-difficulty-adjectives-beginner-esl": { teaching: "Speed and difficulty adjectives are useful for describing tasks, games, and abilities. Contrast the cards through actions so learners can feel fast, slow, easy, difficult, careful, and dangerous.", language: ["This game is easy.", "Please walk slowly and carefully."], activityGuide: "Set up a short task circuit. Learners match an adjective card to each task and explain why it is easy, difficult, fast, or slow." },
  "sports-vocabulary-beginner-esl": { teaching: "Sports vocabulary supports likes, abilities, equipment, and team language. Let learners sort the cards by where or how a sport is played before asking for personal opinions.", language: ["Do you play tennis?", "I can play badminton."], activityGuide: "For Sports Charades, learners mime a sport card. The class guesses and asks one follow-up question about playing it." },
  "thinking-verbs-beginner-esl": { teaching: "Thinking verbs help learners talk about learning itself: guessing, knowing, remembering, and forgetting. They are particularly useful in games where the language describes a real classroom action.", language: ["I think it is a lion.", "Can you remember this word?"], activityGuide: "Use Thinking Mime by acting out a thinking situation. Learners choose the best verb card and explain their choice in a short sentence." },
  "time-vocabulary-beginner-esl": { teaching: "Time vocabulary becomes meaningful when learners connect clock faces to daily routines and timetables. Practise listening as well as reading by moving clock hands or matching time cards.", language: ["What time is it? It’s three o’clock.", "I go to school at eight o’clock."], activityGuide: "For Clock Corners, place time cards around the room. Say a time or show a routine, and learners move to the matching clock." },
  "toys-vocabulary-beginner-esl": { teaching: "Toy vocabulary creates a familiar context for colours, size, possession, and simple preferences. Use the cards for asking, choosing, and describing rather than only naming.", language: ["Have you got a teddy bear?", "My favourite toy is a robot."], activityGuide: "Set up a toy shop role play. One learner asks for a toy card and another gives the matching picture with a polite response." },
  "transportation-vocabulary-beginner-esl": { teaching: "Transportation cards support questions about how people travel and clear sorting by land, air, and water. They also lead naturally into school journeys and travel choices.", language: ["How do you go to school? I go by bus.", "A plane travels in the air."], activityGuide: "For the transportation survey, learners ask classmates about their journey to school and make a class tally from the vehicle cards.", relatedTopic: "transportation" },
  "travel-actions-verbs-beginner-esl": { teaching: "Travel-action verbs give learners language for a journey from leaving home to arriving somewhere new. Sequence the cards to practise first, next, and finally.", language: ["We pack our bags before we travel.", "Let’s get on the train."], activityGuide: "Use a journey sequence race: pairs arrange the travel actions, then narrate the route with the cards in order." },
  "travel-routes-prepositions-beginner-esl": { teaching: "Route language needs a map and a destination. Use these action and preposition phrases with a simple town plan so learners can follow and give directions.", language: ["Walk along this road.", "Go up the hill and cross the bridge."], activityGuide: "Give each pair a map and a destination. One learner guides a counter with the route cards while the other checks every movement." },
  "weather-adjectives-beginner-esl": { teaching: "Weather adjectives make a daily classroom routine more precise. Contrast the cards with gestures, seasons, and clothing choices so learners can talk about conditions beyond sunny and rainy.", language: ["It is hot and dry today.", "I wear boots when it is wet."], activityGuide: "Create a weather wardrobe challenge: pairs choose clothes for a weather card, then explain why the outfit matches the condition.", relatedTopic: "weather" },
  "where-things-are-prepositions-beginner-esl": { teaching: "These location phrases help learners describe a scene with more detail than in and on. Use objects and pictures to show behind, in front of, between, near, far from, and among.", language: ["The cat is behind the chair.", "The tree is near the house."], activityGuide: "For Find the Object, one learner hides a token in a picture scene and gives a location clue while their partner identifies it." },
};

export function getLessonPackTeaching(slug: string): LessonPackTeaching | undefined {
  return LESSON_PACK_TEACHING[slug];
}
