-- Classendo administrator authorization and append-only audit trail.
-- Run once in the Supabase SQL editor before bootstrapping the first owner.

create table if not exists public.admin_memberships (
  user_id uuid primary key references auth.users (id) on delete cascade,
  role text not null check (role in ('owner', 'admin', 'moderator')),
  created_at timestamptz not null default now(),
  created_by uuid references auth.users (id) on delete set null,
  updated_at timestamptz not null default now()
);

comment on table public.admin_memberships is
  'Server-authoritative Classendo administrator roles. Never infer these roles from profiles or client metadata.';

alter table public.admin_memberships enable row level security;

drop policy if exists "admin_memberships_select_own" on public.admin_memberships;
create policy "admin_memberships_select_own"
  on public.admin_memberships
  for select
  to authenticated
  using (user_id = (select auth.uid()));

revoke all on table public.admin_memberships from anon;
revoke insert, update, delete, truncate, references, trigger
  on table public.admin_memberships
  from authenticated;
grant select on table public.admin_memberships to authenticated;
grant all on table public.admin_memberships to service_role;

create index if not exists admin_memberships_role_idx
  on public.admin_memberships (role);

create unique index if not exists admin_memberships_single_owner_idx
  on public.admin_memberships (role)
  where role = 'owner';

create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users (id) on delete set null,
  action text not null,
  target_type text not null,
  target_id text,
  before_state jsonb,
  after_state jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

comment on table public.admin_audit_logs is
  'Append-only record of privileged Classendo actions. Inserts are performed by trusted server code.';

alter table public.admin_audit_logs enable row level security;

revoke all on table public.admin_audit_logs from anon, authenticated;
grant select, insert on table public.admin_audit_logs to service_role;
grant usage, select on sequence public.admin_audit_logs_id_seq to service_role;

create index if not exists admin_audit_logs_actor_created_idx
  on public.admin_audit_logs (actor_user_id, created_at desc);

create index if not exists admin_audit_logs_target_created_idx
  on public.admin_audit_logs (target_type, target_id, created_at desc);

create or replace function public.prevent_admin_audit_log_changes()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  raise exception 'admin_audit_logs is append-only';
end;
$$;

revoke all on function public.prevent_admin_audit_log_changes() from public;

drop trigger if exists admin_audit_logs_append_only
  on public.admin_audit_logs;
create trigger admin_audit_logs_append_only
  before update or delete on public.admin_audit_logs
  for each row execute function public.prevent_admin_audit_log_changes();

create or replace function public.bootstrap_first_admin_owner(target_user_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  existing_owner_id uuid;
  previous_role text;
begin
  if not exists (
    select 1 from auth.users where id = target_user_id
  ) then
    raise exception 'Target authentication user does not exist';
  end if;

  select user_id
    into existing_owner_id
    from public.admin_memberships
   where role = 'owner'
   limit 1;

  if existing_owner_id is not null and existing_owner_id <> target_user_id then
    raise exception 'An owner already exists; use the authenticated owner-management workflow';
  end if;

  select role
    into previous_role
    from public.admin_memberships
   where user_id = target_user_id;

  if previous_role = 'owner' then
    return jsonb_build_object(
      'changed', false,
      'user_id', target_user_id,
      'role', 'owner'
    );
  end if;

  insert into public.admin_memberships (
    user_id,
    role,
    created_by,
    updated_at
  )
  values (
    target_user_id,
    'owner',
    target_user_id,
    now()
  )
  on conflict (user_id) do update
    set role = excluded.role,
        updated_at = now();

  insert into public.admin_audit_logs (
    actor_user_id,
    action,
    target_type,
    target_id,
    before_state,
    after_state,
    metadata
  )
  values (
    target_user_id,
    'admin.owner_bootstrapped',
    'admin_membership',
    target_user_id::text,
    case
      when previous_role is null then null
      else jsonb_build_object('role', previous_role)
    end,
    jsonb_build_object('role', 'owner'),
    jsonb_build_object('source', 'bootstrap_first_admin_owner')
  );

  return jsonb_build_object(
    'changed', true,
    'user_id', target_user_id,
    'role', 'owner'
  );
end;
$$;

revoke all on function public.bootstrap_first_admin_owner(uuid)
  from public, anon, authenticated;
grant execute on function public.bootstrap_first_admin_owner(uuid) to service_role;
