import { ChevronLeft, ChevronRight, Flag, Images, PlusCircle, Search, ShieldAlert } from "lucide-react";
import Image from "next/image";
import Link from "next/link";

import { AdminCommunityReportActions } from "@/components/admin/AdminCommunityReportActions";
import { AdminCreatorImageActions } from "@/components/admin/AdminCreatorImageActions";
import { AdminQuickCommunitySetForm } from "@/components/admin/AdminQuickCommunitySetForm";
import { requireAdmin } from "@/lib/admin/auth";
import { ADMIN_COMMUNITY_PAGE_SIZE, getAdminCommunityReports, getAdminCommunitySets, getAdminCommunitySummary, getAdminCreatorImages } from "@/lib/admin/community";

const dateFormatter = new Intl.DateTimeFormat("en", { dateStyle: "medium" });
function first(value: string | string[] | undefined) { return Array.isArray(value) ? value[0] ?? "" : value ?? ""; }
function pageNumber(value: string) { const parsed = Number.parseInt(value, 10); return Number.isFinite(parsed) && parsed > 0 ? parsed : 1; }
function date(value: string | null) { if (!value) return "—"; const parsed = new Date(value); return Number.isNaN(parsed.getTime()) ? "—" : dateFormatter.format(parsed); }
function owner(item: { username: string | null; displayName: string | null; email: string | null }) { return item.username || item.displayName || item.email || "Deleted user"; }
function setState(item: { deletedAt: string | null; hiddenAt: string | null; isFeatured: boolean; isPublic: boolean }) { if (item.deletedAt) return "Deleted"; if (item.hiddenAt) return "Hidden"; if (item.isFeatured) return "Featured"; return item.isPublic ? "Public" : "Private"; }
function href(view: string, params: Record<string, string | number | undefined> = {}) { const search = new URLSearchParams({ view }); for (const [key, value] of Object.entries(params)) if (value && value !== "all" && value !== 1) search.set(key, String(value)); return `/admin/community?${search}`; }

export default async function AdminCommunityPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const raw = await searchParams;
  const view = ["sets", "reports", "images", "create"].includes(first(raw.view)) ? first(raw.view) : "sets";
  const query = first(raw.q).trim();
  const status = first(raw.status) || (view === "reports" ? "pending" : "all");
  const requestedPage = pageNumber(first(raw.page));
  const administrator = await requireAdmin();
  const [summary, result] = await Promise.all([
    getAdminCommunitySummary(),
    view === "reports" ? getAdminCommunityReports({ status, page: requestedPage })
      : view === "images" ? getAdminCreatorImages({ status, page: requestedPage })
        : view === "sets" ? getAdminCommunitySets({ query, status, page: requestedPage }) : Promise.resolve(null),
  ]);
  const total = result?.total ?? 0;
  const totalPages = Math.max(1, Math.ceil(total / ADMIN_COMMUNITY_PAGE_SIZE));
  const page = Math.min(requestedPage, totalPages);
  const tabs = [{ value: "sets", label: "Community sets", icon: ShieldAlert }, { value: "reports", label: "Reports", icon: Flag }, { value: "images", label: "Creator images", icon: Images }, { value: "create", label: "Create quick set", icon: PlusCircle }];
  const cards = [{ label: "Public sets", value: summary.publicSets }, { label: "Featured", value: summary.featuredSets }, { label: "Hidden", value: summary.hiddenSets }, { label: "Pending reports", value: summary.pendingReports }, { label: "Creator images", value: summary.creatorImages }];

  return <section className="px-5 py-8 sm:px-7 lg:px-10 lg:py-10">
    <div className="flex flex-col justify-between gap-5 border-b border-[#dfe4dc] pb-7 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.22em] text-[#718d63]">Trust and publishing</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-[#2f3a2f] sm:text-4xl">Community moderation</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#6e786d]">Review public lesson sets, member reports, and Creator uploads, or publish administrator-made sets for immediate Community use.</p></div><div className="inline-flex w-fit items-center gap-2 rounded-2xl border border-[#dfe4dc] bg-white px-4 py-3 text-sm text-[#697267]"><Flag className="h-4 w-4 text-[#936954]" /><strong className="text-[#354035]">{summary.pendingReports}</strong> awaiting review</div></div>
    <div className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{cards.map((item) => <article key={item.label} className="rounded-2xl border border-[#dfe4dc] bg-white p-4"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-[#7b8579]">{item.label}</p><p className="mt-2 text-2xl font-semibold text-[#344034]">{item.value}</p></article>)}</div>
    <nav className="mt-6 flex gap-2 overflow-x-auto rounded-2xl border border-[#dfe4dc] bg-white p-2" aria-label="Community moderation sections">{tabs.map(({ value, label, icon: Icon }) => <Link key={value} href={href(value)} className={`inline-flex min-w-max items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-semibold ${view === value ? "bg-[#e7f0e0] text-[#47633c]" : "text-[#697369] hover:bg-[#f5f7f2]"}`}><Icon className="h-4 w-4" />{label}</Link>)}</nav>

    {view === "create" && <div className="mt-5"><AdminQuickCommunitySetForm /></div>}
    {view === "sets" && result && "sets" in result && <><form action="/admin/community" className="mt-5 grid gap-3 rounded-2xl border border-[#dfe4dc] bg-white p-4 md:grid-cols-[minmax(14rem,1fr)_12rem_auto]"><input type="hidden" name="view" value="sets" /><label className="relative"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[#8a9288]" /><input type="search" name="q" defaultValue={query} placeholder="Set title or owner" className="w-full rounded-xl border border-[#d9dfd5] bg-[#fbfcfa] py-2.5 pl-10 pr-3 text-sm outline-none focus:border-[#88a879]" /></label><select name="status" defaultValue={status} className="rounded-xl border border-[#d9dfd5] bg-[#fbfcfa] px-3 py-2.5 text-sm"><option value="all">All sets</option><option value="public">Public</option><option value="featured">Featured</option><option value="reported">Reported</option><option value="hidden">Hidden</option><option value="deleted">Deleted</option></select><button className="btn btn-primary px-5 py-2.5 text-sm">Apply</button></form><div className="mt-5 overflow-hidden rounded-2xl border border-[#dfe4dc] bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[62rem] text-left"><thead className="bg-[#f5f7f2] text-xs font-bold uppercase tracking-[0.1em] text-[#778075]"><tr><th className="px-5 py-3.5">Set</th><th className="px-4 py-3.5">Owner</th><th className="px-4 py-3.5">Status</th><th className="px-4 py-3.5">Cards</th><th className="px-4 py-3.5">Reports</th><th className="px-4 py-3.5">Created</th><th className="px-5 py-3.5 text-right">Review</th></tr></thead><tbody className="divide-y divide-[#edf0ea]">{result.sets.map((item) => <tr key={item.id}><td className="px-5 py-4"><p className="max-w-64 truncate text-sm font-semibold text-[#364136]">{item.name}</p><p className="mt-1 text-xs text-[#858d83]">{item.tags.slice(0, 3).join(" · ") || "No tags"}</p></td><td className="px-4 py-4 text-sm text-[#5d685d]">{owner(item)}</td><td className="px-4 py-4"><span className="rounded-full bg-[#eef1ea] px-2.5 py-1 text-xs font-semibold text-[#687267]">{setState(item)}</span></td><td className="px-4 py-4 text-sm text-[#657065]">{item.cardCount}</td><td className="px-4 py-4 text-sm font-semibold text-[#8a604e]">{item.pendingReportCount || "—"}</td><td className="px-4 py-4 text-sm text-[#657065]">{date(item.createdAt)}</td><td className="px-5 py-4 text-right"><Link href={`/admin/community/sets/${item.id}`} className="text-sm font-semibold text-[#58754c] hover:underline">Review</Link></td></tr>)}</tbody></table></div>{!result.sets.length && <p className="p-10 text-center text-sm text-[#747e73]">No Community sets match these filters.</p>}</div></>}
    {view === "reports" && result && "reports" in result && <><form action="/admin/community" className="mt-5 flex flex-wrap gap-3 rounded-2xl border border-[#dfe4dc] bg-white p-4"><input type="hidden" name="view" value="reports" /><select name="status" defaultValue={status} className="min-w-48 rounded-xl border border-[#d9dfd5] bg-[#fbfcfa] px-3 py-2.5 text-sm"><option value="all">All reports</option><option value="pending">Pending</option><option value="resolved">Resolved</option><option value="dismissed">Dismissed</option></select><button className="btn btn-primary px-5 py-2.5 text-sm">Apply</button></form><div className="mt-5 grid gap-4 lg:grid-cols-2">{result.reports.map((report) => <article key={report.id} className="rounded-2xl border border-[#dfe4dc] bg-white p-5"><div className="flex items-start justify-between gap-3"><div><Link href={`/admin/community/sets/${report.lessonSetId}`} className="font-semibold text-[#3a4738] hover:underline">{report.lessonSetName}</Link><p className="mt-1 text-xs text-[#818a80]">Reported {date(report.createdAt)} · {report.reporterEmail ?? "Deleted user"}</p></div><span className="rounded-full bg-[#f3eee2] px-2.5 py-1 text-xs font-semibold capitalize text-[#80673e]">{report.status}</span></div><p className="mt-4 whitespace-pre-wrap text-sm leading-6 text-[#596359]">{report.reason}</p>{report.resolutionNote && <p className="mt-3 rounded-lg bg-[#f4f7f1] p-3 text-xs leading-5 text-[#687366]">Resolution: {report.resolutionNote}</p>}<AdminCommunityReportActions reportId={report.id} pending={report.status === "pending"} /></article>)}</div>{!result.reports.length && <p className="mt-5 rounded-2xl border border-[#dfe4dc] bg-white p-10 text-center text-sm text-[#747e73]">No reports match this filter.</p>}</>}
    {view === "images" && result && "images" in result && <><form action="/admin/community" className="mt-5 flex flex-wrap gap-3 rounded-2xl border border-[#dfe4dc] bg-white p-4"><input type="hidden" name="view" value="images" /><select name="status" defaultValue={status} className="min-w-48 rounded-xl border border-[#d9dfd5] bg-[#fbfcfa] px-3 py-2.5 text-sm"><option value="all">All images</option><option value="ready">Available</option><option value="rejected">Hidden</option><option value="deleted">Deleted</option></select><button className="btn btn-primary px-5 py-2.5 text-sm">Apply</button></form><div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{result.images.map((item) => <article key={item.id} className="overflow-hidden rounded-2xl border border-[#dfe4dc] bg-white"><div className="relative aspect-[4/3] bg-[#edf0ea]">{item.imageUrl ? <Image src={item.imageUrl} alt={item.originalFilename} fill unoptimized className="object-contain" /> : <div className="grid h-full place-items-center text-sm text-[#7b8479]">Preview unavailable</div>}</div><div className="p-4"><div className="flex justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-semibold text-[#394439]">{item.originalFilename}</p><p className="mt-1 truncate text-xs text-[#818a80]">{owner(item)}</p></div><span className="h-fit rounded-full bg-[#eef1ea] px-2.5 py-1 text-xs font-semibold capitalize text-[#687267]">{item.deletedAt ? "deleted" : item.status}</span></div><p className="mt-3 text-xs text-[#778176]">Used by {item.creatorCardCount + item.lessonCardCount} card{item.creatorCardCount + item.lessonCardCount === 1 ? "" : "s"} · {Math.ceil(item.sizeBytes / 1024)} KB</p>{item.moderationNote && <p className="mt-2 text-xs leading-5 text-[#8a604e]">{item.moderationNote}</p>}<AdminCreatorImageActions imageId={item.id} available={item.status === "ready" && !item.deletedAt} deleted={Boolean(item.deletedAt)} canDelete={administrator.role === "owner"} mfaVerified={administrator.assuranceLevel === "aal2"} /></div></article>)}</div>{!result.images.length && <p className="mt-5 rounded-2xl border border-[#dfe4dc] bg-white p-10 text-center text-sm text-[#747e73]">No Creator images match this filter.</p>}</>}
    {view !== "create" && totalPages > 1 && <nav className="mt-5 flex items-center justify-between rounded-2xl border border-[#dfe4dc] bg-white px-4 py-3 text-sm"><Link aria-disabled={page <= 1} href={href(view, { q: query, status, page: Math.max(1, page - 1) })} className={`inline-flex items-center gap-1 font-semibold ${page <= 1 ? "pointer-events-none opacity-35" : "text-[#58704e]"}`}><ChevronLeft className="h-4 w-4" />Previous</Link><span className="text-[#747d73]">Page {page} of {totalPages}</span><Link aria-disabled={page >= totalPages} href={href(view, { q: query, status, page: Math.min(totalPages, page + 1) })} className={`inline-flex items-center gap-1 font-semibold ${page >= totalPages ? "pointer-events-none opacity-35" : "text-[#58704e]"}`}>Next<ChevronRight className="h-4 w-4" /></Link></nav>}
  </section>;
}
